dependencies:
  - allOf:
    - cert-manager
    - krakend-operator-crds
environmentKinds:
  - tenant
  - legacy
  - onprem
values:
  apiserverIP:
    displayName: API server IP
    computed:
      template: '"{{ .Env.apiserver_endpoint }}"'
  customCrds.replicator:
    displayName: Replicator enabled
    config:
      type: bool
    computed:
      template: 'true'
  controllerManager.manager.env.debug:
    description: Enable debug logging
    displayName: Debug
    config:
      type: bool
  controllerManager.manager.env.netpolEnabled:
    displayName: Network policy enabled
    computed:
      template: '{{ ne .Kind "onprem" }}'
  replicator.krakend.webproxy:
    displayName: Use webproxy for krakend
    computed:
      template: '{{ eq .Kind "onprem" }}'
  replicator.krakend.ingressDomain:
    displayName: Krakend ingress domain
    description: The domain to use for the ingress
    config:
      type: string
  replicator.krakend.ingressClassName:
    displayName: Krakend ingress class name
    description: The class to use for the ingress
    config:
      type: string
  replicator.krakend.maskinporten.jwkUrl:
    displayName: Krakend Maskinporten JWK URL
    description: The JWK URL to use for Maskinporten
    config:
      type: string
  replicator.krakend.maskinporten.issuer:
    displayName: Krakend Maskinporten issuer
    description: The issuer to use for Maskinporten
    config:
      type: string
  replicator.krakend.azuread.jwkUrl:
    displayName: Krakend Azure AD JWK URL
    description: The JWK URL to use for Azure AD
    config:
      type: string
  replicator.krakend.azuread.issuer:
    displayName: Krakend Azure AD issuer
    description: The issuer to use for Azure AD
    config:
      type: string
