krakend:
  krakend:
    env:
      - name: USAGE_DISABLE
        value: "1"
    extraConfig:
      router:
        "@comment": "The health endpoint checks do not show in the logs"
        logger_skip_paths:
          - "/__health"
      "telemetry/opencensus":
        sample_rate: 100
        exporters:
          prometheus:
            port: 9091
            namespace: "krakend"
            tag_host: false
            tag_path: true
            tag_method: true
            tag_status_code: false
  serviceMonitor:
    enabled: true
  service:
    metrics:
      enabled: true
      port: 9091
      targetPort: 9091
  replicaCount: 2
  image:
    registry: docker.io
    repository: devopsfaith/krakend
    tag: 2.5.1
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 1000
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
  ingress:
    enabled: true
    className: "nais-ingress-external"
    annotations: {}
