apiVersion: krakend.nais.io/v1
kind: ApiEndpoints
metadata:
  name: debugapp-krakend
spec:
  auth:
    name: maskinporten
    cache: true
    debug: true
    scope:
      - "nav:aura:krakend.debugapp"
  endpoints:
    - path: /debugapp
      method: GET
      forwardHeaders:
        - Authorization
      backendHost: http://debugapp-krakend.aura.svc.nais.local
      backendPath: /
  openEndpoints:
    - path: /debugapp/doc
      method: GET
      backendHost: http://debugapp-krakend.aura.svc.nais.local
      backendPath: /doc
