apiVersion: krakend.nais.io/v1
kind: ApiEndpoints
metadata:
  name: up
spec:
  appName: up
  auth:
    name: azuread
    cache: true
    debug: true

  endpoints:
    - path: /up/azuread
      method: GET
      forwardHeaders:
        - Authorization
      backendHost: http://up.aura.svc.nais.local
      backendPath: /