{{- if .Values.customCrds.monitoring }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "krakend-operator.fullname" . }}-controller-manager-metrics-monitor
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: krakend
    app.kubernetes.io/part-of: krakend
    control-plane: controller-manager
  {{- include "krakend-operator.labels" . | nindent 4 }}
spec:
  endpoints:
    - path: /metrics
      port: http
      scheme: http
  selector:
    matchLabels:
      control-plane: controller-manager
      {{- include "krakend-operator.selectorLabels" . | nindent 6 }}
{{- end}}