{{ if and .Values.apiserverIP .Values.controllerManager.manager.env.netpolEnabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-apiserver
spec:
  egress:
    - ports:
        - port: 443
          protocol: TCP
      to:
        - ipBlock:
            cidr: {{ .Values.apiserverIP }}/32
  ingress:
    - ports:
        - port: 9443
          protocol: TCP
      from: []
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}
  policyTypes:
    - Egress
    - Ingress
{{ end }}