{{-if .Values.customCrds.certmanager }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "krakend-operator.fullname" . }}-selfsigned-issuer
  labels:
  {{- include "krakend-operator.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{-end}}