{{- if .Values.customCrds.certmanager }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "krakend-operator.fullname" . }}-serving-cert
  labels:
  {{- include "krakend-operator.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "krakend-operator.fullname" . }}-webhook-service.{{ .Release.Namespace
    }}.svc'
  - '{{ include "krakend-operator.fullname" . }}-webhook-service.{{ .Release.Namespace
    }}.svc.{{ .Values.kubernetesClusterDomain }}'
  issuerRef:
    kind: Issuer
    name: '{{ include "krakend-operator.fullname" . }}-selfsigned-issuer'
  secretName: krakend-operator-webhook-server-cert
{{- end }}